name: Continuous Integration

on:
  workflow_dispatch:
  push:

jobs:

  build-release:
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments
        os: [macos-latest, ubuntu-latest]
        swift-version: ['6.1', '6.2', '6.3']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: swift-actions/setup-swift@v3
        with:
          swift-version: ${{ matrix.swift-version }}
          skip-verify-signature: true
      - name: Echo Swift version
        run: swift --version
      - name: Check a Release build
        run: swift build --disable-automatic-resolution -c release

  test:
    strategy:
      matrix:
        # https://github.com/actions/virtual-environments
        os: [macos-latest, ubuntu-latest]
        swift-version: ['6.1', '6.2', '6.3']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - uses: swift-actions/setup-swift@v3
        with:
          swift-version: ${{ matrix.swift-version }}
          skip-verify-signature: true
      - name: Echo Swift version
        run: swift --version
      - name: Test
        run: swift test --disable-automatic-resolution
